// LAB_EXPERIMENTS — safe for client components (no fs dependency)
// AUTO-GENERATED by scripts/sync-lab.sh — edit content/lab/experiments.json instead

export interface LabExperiment {
  id: number;
  title: string;
  status: "active" | "completed" | "paused";
  week?: string;
  description: string;
  details?: string;
  link?: string;
  linkLabel?: string;
}

export const LAB_EXPERIMENTS: LabExperiment[] = [
  {
    id: 1,
    title: "LinkedIn Visibility Sprint",
    status: "active",
    week: "Week 2 of 4",
    description:
      "Testing whether a structured 4-week posting cadence — one AI post, one Bitcoin post, one personal take — meaningfully lifts profile impressions and newsletter subscribers. Tracking weekly deltas in a shared doc.",
    details:
      "Current results: +34% profile views in week 1. Hypothesis: consistent cross-topic posting creates a compound identity signal that rewards both audiences. Next metric to watch: subscriber conversion rate from LinkedIn traffic vs. direct.",
  },
  {
    id: 2,
    title: "Enterprise Agent Self-Learning Loop",
    status: "active",
    description:
      "An agent that reviews its own past outputs, identifies recurring failure patterns, and rewrites its system prompt accordingly. No human intervention after the initial setup. Measuring output quality degradation or improvement over 30 iterations.",
    details:
      "Architecture: a reviewer agent scores each production run against a rubric, writes findings to a structured log, and a rewriter agent synthesizes the last 10 logs into a refined system prompt. Running on 30-iteration cycles. Currently on iteration 8. Initial quality score: 6.2/10. Current: 7.4/10.",
  },
  {
    id: 3,
    title: "R&D Council",
    status: "active",
    description:
      "A multi-agent council that convenes weekly to evaluate content strategy, research directions, and site experiments. Each agent plays a distinct role: Strategist, Editor, Researcher, Devil's Advocate.",
    details:
      "Four sessions completed. The council has approved the production launch, greenlit halving coverage, and deferred the Lab expansion pending subscriber growth. View the full council log and latest memo for session transcripts.",
    link: "/council",
    linkLabel: "View Council Log",
  }
];
