#!/usr/bin/env bash
set -euo pipefail

# ── Paths ──────────────────────────────────────────────────────────────────
SITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JSON_SRC="$SITE_DIR/content/lab/experiments.json"
DATA_OUT="$SITE_DIR/src/lib/data.ts"

# ── Validate source ──────────────────────────────────────────────────────────
[[ -f "$JSON_SRC" ]] || { echo "ERROR: $JSON_SRC not found" >&2; exit 1; }

echo "Syncing lab experiments..."
echo "  Source: $JSON_SRC"
echo "  Target: $DATA_OUT"

# ── Generate data.ts via Python ─────────────────────────────────────────────
python3 - "$JSON_SRC" "$DATA_OUT" <<'PYTHON'
import sys
import json

json_src, data_out = sys.argv[1:]

experiments = json.loads(open(json_src).read())

def ts_str(s):
    """Escape a string for use in a TypeScript string literal."""
    return s.replace('\\', '\\\\').replace('"', '\\"')

lines = []
lines.append('// LAB_EXPERIMENTS — safe for client components (no fs dependency)')
lines.append('// AUTO-GENERATED by scripts/sync-lab.sh — edit content/lab/experiments.json instead')
lines.append('')
lines.append('export interface LabExperiment {')
lines.append('  id: number;')
lines.append('  title: string;')
lines.append('  status: "active" | "completed" | "paused";')
lines.append('  week?: string;')
lines.append('  description: string;')
lines.append('  details?: string;')
lines.append('  link?: string;')
lines.append('  linkLabel?: string;')
lines.append('}')
lines.append('')
lines.append('export const LAB_EXPERIMENTS: LabExperiment[] = [')

for i, exp in enumerate(experiments):
    comma = '' if i == len(experiments) - 1 else ','
    lines.append('  {')
    lines.append(f'    id: {exp["id"]},')
    lines.append(f'    title: "{ts_str(exp["title"])}",')
    lines.append(f'    status: "{exp["status"]}",')
    if 'week' in exp:
        lines.append(f'    week: "{ts_str(exp["week"])}",')
    lines.append(f'    description:')
    lines.append(f'      "{ts_str(exp["description"])}",')
    if 'details' in exp:
        lines.append(f'    details:')
        lines.append(f'      "{ts_str(exp["details"])}",')
    if 'link' in exp:
        lines.append(f'    link: "{ts_str(exp["link"])}",')
    if 'linkLabel' in exp:
        lines.append(f'    linkLabel: "{ts_str(exp["linkLabel"])}",')
    lines.append(f'  }}{comma}')

lines.append('];')
lines.append('')

open(data_out, 'w').write('\n'.join(lines))
print(f"  Written {len(experiments)} experiment(s) to {data_out}")
PYTHON

# ── Git: commit only if data.ts changed ─────────────────────────────────────
cd "$SITE_DIR"
GIT_STATUS=$(git status --porcelain src/lib/data.ts content/lab/ 2>/dev/null || true)

if [[ -z "$GIT_STATUS" ]]; then
    echo "No changes detected — nothing to commit."
else
    echo "Changes detected:"
    echo "$GIT_STATUS"
    git add src/lib/data.ts content/lab/
    git commit -m "chore(lab): sync experiments from JSON content"
    git push
    echo "Committed and pushed."
fi

echo "Done."
